# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.0.0.20"
  config.vm.synced_folder "../../Documents/git", "/git" , owner: "root", group: "root"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "config.sh"
  config.vm.provision "shell", path: "db-mysql.sh"
  config.vm.provision "shell", path: "db-postgresql.sh"
  config.vm.provision "shell", path: "desk-mate.sh"

   config.ssh.forward_agent = true
   config.ssh.forward_x11 = true

   config.vm.provider :virtualbox do |vb|
   	vb.name = "Pineboo Devel"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    end
end